name: "Firebase Publish Action"
description: "Upload file to storage & add entry to Firestore"
inputs:
  filename:
    description: "The file path to uploader (exe or apk)"
    required: true
  sa-key:
    description: "Service Account JSON content"
    required: true
  bucket:
    description: "The storage bucket name"
    required: true
  dst:
    description: "The destination folder in the bucket"
    required: true
    default: "releases"
outputs:
  url:
    description: "The storage URL of the uploaded file"
runs:
  using: "node12"
  main: "dist/index.js"
